export const SOCKET_CONNECTED = 'SOCKET_CONNECTED'
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED'
export const SOCKET_STATE_UPDATE = 'SOCKET_STATE_UPDATE'
export const SOCKET_SET = 'SOCKET_SET'