export const base = ''
export const jobs = base + '/jobs'
export const jobsNew = jobs + '/new'
export const jobsCompleted = jobs + '/completed'
export const jobsRunning = jobs + '/running'
export const jobsSubmitted = jobs + '/submitted'
export const jobsConfigured = jobs + '/configured'